stages:
  - build
  - deploy
 
build-job:
  tags:
    - e-3208
  stage: deploy
  script:
    - echo OK
  only:
    - master
  artifacts:
    paths:
       - README.md
       - lib/src/main/public/unittest.h
       - lib/src/main/cpp/unittest.cpp

linux-build:
  tags:
    - e-3208
  stage: build
  script:
    - cd lib
    - chmod +x ../gradlew
    - ../gradlew build --no-daemon
  only:
    - master

cygwin-build:
  tags:
    - sjz-win10
  stage: build
  script:
    - path c:\cygwin64\bin;%path%
    - cd lib
    - ..\gradlew.bat test --no-daemon
  only:
    - master

mingw-build:
  tags:
    - sjz-win10
  stage: build
  script:
    - path c:\MinGW\bin;%path%
    - cd lib
    - ..\gradlew.bat test --no-daemon
  only:
    - master
    