stages:
  - build
  - deploy
 
build-job:
  tags:
    - e-3208
  stage: deploy
  script:
    - echo OK
  only:
    - master
  artifacts:
    paths:
       - README.md
       - unittest.h
       - unittest.cpp

linux-build:
  tags:
    - e-3208
  stage: build
  script:
    - ./gradlew build --no-daemon
  only:
    - gradle

cygwin-job:
  tags:
    - sjz-win10
  stage: build
  script:
    - path c:\cygwin64\bin;%path%
    - .\gradlew.bat test --no-daemon
  only:
    - gradle

mingw-job:
  tags:
    - sjz-win10
  stage: build
  script:
    - path c:\MinGW\bin;%path%
    - .\gradlew.bat test --no-daemon
  only:
    - gradle
    