name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04-gcc-9

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      # Runs commands 
      - name: environment check
        run: |
          g++ --version
	  - name: installation
	    run: |
		  sudo apt update
		  sudo update-alternatives --remove-all gcc 
          sudo update-alternatives --remove-all g++
		  sudo apt install g++-9
		  sudo update-alternatives --set gcc /usr/bin/gcc-9
		  sudo update-alternatives --set g++ /usr/bin/g++-9
      - name: gradle test
        run: |
          ./gradlew lib:build
          ./gradlew demoTests:test
          find lib/build/tmp/ -name options.txt -print -exec cat {} \;
          find lib/build/tmp/ -name output.txt -print -exec cat {} \;
      - name: gradle build
        run: |
          ./gradlew demoTests:build
      - name: diagnose
        if: ${{ failure() }}
        run: |
          find demoTests/build/tmp/ -name options.txt -print -exec cat {} \;
          find demoTests/build/tmp/ -name output.txt -print -exec cat {} \;
